---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check buildkit version
      ansible.builtin.command: /usr/local/bin/buildctl --version
      register: buildkit_test_output

    - name: Print buildctl --version
      ansible.builtin.debug:
        msg: '{{ buildkit_test_output.stdout }}'
